name: 💡 Feature Request
description: Request a new feature.
title: "💡 "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your feature suggestion. Please provide the following information.

  - type: textarea
    id: feature-details
    attributes:
      label: Description
      description: Please provide a detailed description of the feature.
      placeholder: Please be specific.
    validations:
      required: true

  - type: textarea
    id: feature-goal
    attributes:
      label: Goal
      description: Please describe the expected behavior.
    validations:
      required: true
